# Generated by Django 5.2.16 on 2026-07-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_seed_menu_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Only approved items show on the public website. Items created via CSV import are unapproved by default until reviewed here.'),
        ),
    ]
