# Generated by Django 5.2.16 on 2026-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='is_closed',
            field=models.BooleanField(default=False, help_text="Overrides Open/Close times below — check this to show 'Closed' on the website for this day, even if times are set."),
        ),
    ]
