# Generated by Django 5.2.16 on 2026-07-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seed_site_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='doordash_url',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='qr_ordering_url',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='uber_eats_url',
            field=models.URLField(blank=True, max_length=350),
        ),
    ]
