# Generated by Django 5.2.16 on 2026-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_sitesetting_doordash_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text="A 'View on Google Maps' link for visitors to click (any Google Maps URL works here, including a share link). The embedded map shown on the site is generated automatically from the Address field above, since Google blocks most Maps links from being embedded directly."),
        ),
    ]
