# Generated by Django 5.2.16 on 2026-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_sitesetting_google_maps_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
    ]
