# Generated by Django 5.2.16 on 2026-07-31 15:55

from django.db import migrations, models


def copy_social_urls_to_socials(apps, schema_editor):
    """Carry over any real Instagram/Facebook/TikTok URLs already entered
    on SiteSetting before those columns are dropped below."""
    SiteSetting = apps.get_model("common", "SiteSetting")
    Socials = apps.get_model("common", "Socials")

    site_setting = SiteSetting.objects.filter(pk=1).first()
    if not site_setting:
        return

    Socials.objects.update_or_create(
        pk=1,
        defaults={
            "instagram_url": site_setting.instagram_url,
            "facebook_url": site_setting.facebook_url,
            "tiktok_url": site_setting.tiktok_url,
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_sitesetting_tiktok_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Socials',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.RunPython(copy_social_urls_to_socials, noop_reverse),
        migrations.RemoveField(
            model_name='sitesetting',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='tiktok_url',
        ),
    ]
