# Generated by Django 5.2.16 on 2026-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_socials_remove_sitesetting_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='Must be a real Google Maps EMBED url, not a share link — a normal maps.app.goo.gl/google.com/maps/place link will show \'refused to connect\' when embedded. To get the right one: open Google Maps, search this address, click Share > Embed a map, then copy just the URL from inside the generated <iframe src="..."> code (it will contain /maps/embed). This same link is also used for the \'View on Google Maps\' link.', max_length=350),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='opentable_embed_url',
            field=models.URLField(blank=True, max_length=350),
        ),
    ]
