# Generated by Django 5.2.16 on 2026-08-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_sitesetting_google_maps_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='gift_vouchers_url',
            field=models.URLField(blank=True, max_length=350),
        ),
    ]
