# Generated by Django 5.2.16 on 2026-08-07 11:09

from django.db import migrations, models


def copy_order_online_urls(apps, schema_editor):
    """Carry over any real Uber Eats/DoorDash/pickup/gift-voucher URLs
    already entered on SiteSetting before those columns are dropped
    below — matters most on production, whose real data this needs to
    survive intact."""
    SiteSetting = apps.get_model("common", "SiteSetting")
    OrderOnline = apps.get_model("common", "OrderOnline")

    site_setting = SiteSetting.objects.filter(pk=1).first()
    if not site_setting:
        return

    OrderOnline.objects.update_or_create(
        pk=1,
        defaults={
            "qr_ordering_url": site_setting.qr_ordering_url,
            "uber_eats_url": site_setting.uber_eats_url,
            "doordash_url": site_setting.doordash_url,
            "gift_vouchers_url": site_setting.gift_vouchers_url,
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_sitesetting_gift_vouchers_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_ordering_url', models.URLField(blank=True, max_length=350)),
                ('uber_eats_url', models.URLField(blank=True, max_length=350)),
                ('doordash_url', models.URLField(blank=True, max_length=350)),
                ('gift_vouchers_url', models.URLField(blank=True, max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Online',
                'verbose_name_plural': 'Order Online',
            },
        ),
        migrations.RunPython(copy_order_online_urls, noop_reverse),
        migrations.RemoveField(
            model_name='sitesetting',
            name='doordash_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='gift_vouchers_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='qr_ordering_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='uber_eats_url',
        ),
    ]
