# Generated by Django 5.2.16 on 2026-08-07 11:28

from django.db import migrations, models


def copy_opentable_embed_url(apps, schema_editor):
    """Carry over the real booking widget URL already entered on
    SiteSetting before that column is dropped below — matters most on
    production, whose real value this needs to survive intact."""
    SiteSetting = apps.get_model("common", "SiteSetting")
    Booking = apps.get_model("common", "Booking")

    site_setting = SiteSetting.objects.filter(pk=1).first()
    if not site_setting:
        return

    Booking.objects.update_or_create(
        pk=1,
        defaults={"opentable_embed_url": site_setting.opentable_embed_url},
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_orderonline_remove_sitesetting_doordash_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opentable_embed_url', models.URLField(blank=True, help_text='Embeddable booking widget URL (e.g. NowBookIt, OpenTable) shown on the Book a Table page.', max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
            },
        ),
        migrations.RunPython(copy_opentable_embed_url, noop_reverse),
        migrations.RemoveField(
            model_name='sitesetting',
            name='opentable_embed_url',
        ),
    ]
