# Generated by Django 5.2.16 on 2026-08-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_seed_home_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Story', max_length=200)),
                ('story', models.TextField(default="At Mitch & Antler, we believe a great café is about more than just coffee—it's about creating a place where people feel welcome, connected, and at home.\n\nNestled in the heart of Mitchelton, we've created a space where neighbours become friends, families gather, and visitors can slow down and enjoy exceptional food, specialty coffee, and genuine hospitality. Whether you're stopping by for your morning coffee, catching up with friends over brunch, or enjoying a relaxed lunch, every visit is an opportunity to create memorable moments.\n\nOur menu is thoughtfully crafted using quality ingredients, combining familiar favourites with fresh, modern flavours. Every dish and every cup of coffee is prepared with care, because we believe the little details make all the difference.\n\nMore than anything, Mitch & Antler is built on the values of warmth, kindness, and community. We take pride in knowing our regulars by name while making every first-time guest feel like they've been here before. We're also proudly dog-friendly, so your four-legged companions are always welcome to join you.\n\nThank you for making Mitch & Antler part of your day. We look forward to welcoming you through our doors and sharing many more coffees, conversations, and celebrations together.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
