# Generated by Django 5.2.16 on 2026-08-01 15:13

from django.db import migrations, models


def split_existing_heading(apps, schema_editor):
    """The old combined heading ("Great coffee, honest food, good
    company.") needs splitting into the new two-field form so the real
    content displays exactly as before once the template starts rendering
    hero_heading + hero_heading_accent separately."""
    HomePageContent = apps.get_model("website", "HomePageContent")
    OLD_COMBINED = "Great coffee, honest food, good company."
    for obj in HomePageContent.objects.filter(hero_heading=OLD_COMBINED):
        obj.hero_heading = "Great coffee, honest food,"
        obj.hero_heading_accent = "good company."
        obj.save(update_fields=["hero_heading", "hero_heading_accent"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_aboutpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_heading_accent',
            field=models.CharField(blank=True, default='good company.', help_text="Optional short phrase rendered after the main heading in an italic accent color, e.g. 'good company.' — leave blank to skip it.", max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_heading',
            field=models.CharField(default='Great coffee, honest food,', max_length=200),
        ),
        migrations.RunPython(split_existing_heading, noop_reverse),
    ]
